name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  # print_context:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - env:
  #         EVENT_CONTEXT: ${{ toJSON(github.event) }}
  #       run: |
  #         echo $EVENT_CONTEXT
  #         echo ${{ github.event.inputs == '' }}
  #         echo ${{ github.event.inputs.siteName == '' }}
  #         echo ${{ github.event.inputs.siteName == null }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.10

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm build

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.10

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Check formatting
        run: pnpm format
